version: '3'
services:
  web:
    image: webdevops/php-apache:5.6
    ports:
      - "443:443"
    volumes:
      - .:/app
    environment:
      - WEB_DOCUMENT_ROOT="/app/public"
    env_file:
      - .env
